### ISSUE TITLE
Add "about" snippet to home page

### ISSUE THREAD

**Issue by jeancflanagan** [jeancflanagan/jeancflanagan#136]
Add a small snippet "about me" to the home page (with a link to "read more" on the about page).

**Comment by opattison** [comment]
@jeancflanagan Some content for this in the next week maybe? I can start designing for it.

**Comment by jeancflanagan** [comment]
This may be too long, but it's a start:

I'm interested in pushing science education and communication forward by getting research out of the ivory tower and into practice. I've immersed myself in education research and national standards for AAAS, PLOS, and Smithsonian, focusing on the development of curriculum, assessments, and professional development. This site is a personal archive of my writing, photography, and other projects. Find out more about me.

**Comment by opattison** [comment]
Attached to #142; will design something soon.
