### ISSUE TITLE
Restructure home page

### ISSUE THREAD

**Issue by jeancflanagan** [jeancflanagan/jeancflanagan#137]
Instead of populating the home page with the 4 most recent writing items followed by the 4 most recent photography items, allow it to be hand-curated, without a divide between writing and photography.

Depending on the design for the about snippet, which will add content to the page, we might consider featuring fewer than 8 items.

**Comment by jeancflanagan** [comment]
This will now be the main destination for the website, including a brief "about" section, professional overview, and portfolio. 

Articles and photo sets will remain archived here, and selectively linked to from the home page, but will no longer be the primary feature of the site.

**Comment by jeancflanagan** [comment]
Typography ideas:

- [Brioni Sans](https://www.typotheque.com/fonts/brioni_sans)

**Comment by jeancflanagan** [comment]
Try the section heads in hsl(198, 20%, 32%);

**Comment by opattison** [comment]
Will be solved by PR #174
